/*
<Esto generar un pdf de dos archivos de formato xml pasarlo a un o formato de pdf >
    Copyright 2023  Agrega

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package PDFMaker;

import java.awt.List;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import com.itextpdf.text.*;
import com.itextpdf.text.Chunk;
//import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import static com.itextpdf.text.Font.BOLD;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfImportedPage;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.opencsv.*;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.text.DateFormat;

/**
 *
 * @author roberto
 */
public class pdfx extends javax.swing.JFrame {
int cont = 0;
String templatecuerpo = "";
String template = "";
int cantprogramas = 0 ;
String name = "";
String archivodetallename = "0";

int primero = 0 ;
int ultimo  = 0 ; 

    /**
     * Creates new form Menu
     */
    public pdfx() {
        initComponents();
        
//        fieldmaster.setEditable(false);
//        fieldnombre.setEditable(false);
       // fieldprefijo.setText("ESTADOCUENTA");
      //  fieldprefijo.setEditable(false);
        NodeList nList1;
        NodeList nList2;
        this.setResizable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        fieldtemplate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        fielddetalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldcontrol = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        titulo3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        fieldpublicacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        generar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        titulo4 = new javax.swing.JLabel();
        Correlativo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        titulo5 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        titulo1.setBackground(new java.awt.Color(204, 204, 204));
        titulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo1.setText("Templates Directory");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fieldtemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldtemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        titulo2.setBackground(new java.awt.Color(204, 204, 204));
        titulo2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo2.setText("Informacion de Archivos");

        fielddetalle.setEnabled(false);
        fielddetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fielddetalleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Archivo control :");

        fieldcontrol.setEnabled(false);
        fieldcontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcontrolActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Archivo detalle :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldcontrol, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(fielddetalle)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fielddetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldcontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("v.11");

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        titulo3.setBackground(new java.awt.Color(204, 204, 204));
        titulo3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo3.setText("Publicacion :");

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        fieldpublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpublicacionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Directorio de publicacion:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldpublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldpublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        titulo4.setBackground(new java.awt.Color(204, 204, 204));
        titulo4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo4.setText("Correlativo :");

        Correlativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrelativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correlativo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Correlativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        titulo5.setBackground(new java.awt.Color(204, 204, 204));
        titulo5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo5.setText("Resultado :");

        resultado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        resultado.setText("Standby");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(27, 27, 27)
                            .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldpublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpublicacionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/Archivos");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fieldpublicacion.setText(chooser.getSelectedFile().getAbsolutePath());
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());         // TODO add your handling code here:
    }    
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/datos");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fieldcontrol.setText(chooser.getSelectedFile().getAbsolutePath());
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/datos");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());
            fielddetalle.setText(chooser.getSelectedFile().getAbsolutePath());
            archivodetallename = chooser.getSelectedFile().getName();
            
        }
    //    JOptionPane.showMessageDialog(null, archivodetallename);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldcontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcontrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcontrolActionPerformed

    private void fielddetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fielddetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fielddetalleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

   
       
       
     //   JOptionPane.showMessageDialog(null, System.getProperty("user.dir")+"/Template");
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/Template");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fieldtemplate.setText(chooser.getSelectedFile().getAbsolutePath());
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());   
            
        

   
// TODO add your handling code here:
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
      
        
        
        if(fieldtemplate.getText().isEmpty() || fielddetalle.getText().isEmpty() || fieldcontrol.getText().isEmpty() || fieldpublicacion.getText().isEmpty() || Correlativo.getText().isEmpty() ){
       
        JOptionPane.showMessageDialog(null,"Favor llenar todos los campos");
        
        }else{
          resultado.setText("In Process...");
          resultado.setForeground(Color.gray);
         Nodos();
         
         
            
        }
        
        
       
    }//GEN-LAST:event_generarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//JOptionPane.showMessageDialog(null, "test");
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CorrelativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrelativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorrelativoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public void Nodos(){
        generar.setVisible(false);
        JOptionPane.showMessageDialog(null, "Este proceso puede tardar varios segundos, favor esperar mensaje de confirmacion");
        
        try{
            File Xml1= new File(fielddetalle.getText());
            File Xml2= new File(fieldcontrol.getText());
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc1 = dBuilder.parse(Xml1);
            Document doc2 = dBuilder.parse(Xml2);
            
            
            
            doc1.getDocumentElement().normalize();
            
           NodeList nList1 = doc1.getElementsByTagName("Detalle");
           NodeList nList2 = doc1.getElementsByTagName("MensajePie");
           // JOptionPane.showMessageDialog(null, doc1.getElementsByTagName("Mensajes").getLength());
           NodeList nList5 = doc1.getElementsByTagName("Mensajes");
           NodeList nList3 = doc2.getElementsByTagName("Encabezado");
            NodeList nList4 = doc2.getElementsByTagName("Programa");
            //System.out.println("ok");
            
         //   primero = nList3.item(0).
          //  int cantcab = nList3.item(nList3.getLength()).getAttributes().equals("Datos");
           /*
                   Node nNode = nList3.item(nList3.getLength()); 
	           Element eElement = (Element) nNode;
                   String numfinal = eElement.getAttribute("Datos");
                       
                   nNode = nList3.item(nList3.getLength()); 
	           eElement = (Element) nNode;
                   String numinicial = eElement.getAttribute("Datos");
            
            */
            //Ciclo Generacion PDF 1 por 1 --------------------------------------------------------------------------------------------------------------
            
                 Node nNode = nList3.item(0); 
                 Element eElement = (Element) nNode;
                 String inicio = eElement.getAttribute("Datos");
                 
                 Node nNode2 = nList3.item(nList3.getLength()-1); 
                 Element eElement2 = (Element) nNode2;
                 String ultimo2 = eElement2.getAttribute("Datos");
                 
                 primero = Integer.parseInt(inicio);
                 ultimo = Integer.parseInt(ultimo2);
                 
                 int contnum1 = 0;
            
                 //JOptionPane.showMessageDialog(null,primero + " + "+ ultimo);
            
            for (int temp = primero; temp < (ultimo+1); temp++) {//For para Encabezados
                
		DecimalFormat decimalFormat = new DecimalFormat("0000000");
                String cuenta = decimalFormat.format(temp);
                
            //    JOptionPane.showMessageDialog(null, cuenta);
                
                int cantpdf = nList3.getLength();
              //  cantprogramas = nList4.getLength();
              //  String cuenta= Integer.toString(temp+1);
                List ListTemp2 = detalle(cuenta,nList1,nList5);
                List ListD= Mensajepie(cuenta, nList2, ListTemp2);
                List ListTemp1 = Encabezado(contnum1,nList3);
                List ListE=Programa(cuenta, nList4, ListTemp1);
                List ListF=Mensaje7(cuenta, nList5);
		List ListG=Mensaje8(cuenta, nList5);
                
                
                System.out.println(cuenta);
              //  JOptionPane.showMessageDialog(null,ListF.getItemCount() );
                
                PDF(ListD, ListE, ListF, cantpdf, ListG);
                contnum1++;
                }
            //JOptionPane.showMessageDialog(null, ListF);
            JOptionPane.showMessageDialog(null, "Proceso creado exitosamente");
            resultado.setText("Success!");
        resultado.setForeground(Color.green);
        }catch (Exception e) {
            try {
                log(e.getMessage());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(pdfx.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "ERROR :1. Seleccionar los archivos detalle y control correctos \n 2. Seleccionar la carpeta de templates correcto." );
	e.printStackTrace();
    }
        
        generar.setVisible(true);
        
        
        
      
    }
    
    
    //Fin de ciclo PDF------------------------------------------------------------------------------------------------------------------------------------
    
    
    
    public void PDF(List ListD, List ListE, List ListF, int cantpdf, List ListG) throws DocumentException, BadElementException, IOException {
      
       cont++;
       int fila = 615;
       String nombredelpdf = "";
       int pagina = 1 ;
       int repeticiones = 1;
       BaseColor bs = new BaseColor(0,0,0);
       
       
       
       String subproducto = "subproducto";
    String folder = "";
  
    //JOptionPane.showMessageDialog(null, ListE.getItem(21));
   if (ListE.getItem(21).contains("1")){
    subproducto = "DP";
    folder = "puntosX";
    //JOptionPane.showMessageDialog(null,"Tipo de Tarjeta : "+ListE.getItem(1));
   
   String tipotarjeta = ListE.getItem(1);
   
    
   
   //-------------------Seleccion de Template----------------------------------//
   if (tipotarjeta.contains("BLACK INFINITE")){
   template = fieldtemplate.getText() + "\\template.pdf";
   }else if (tipotarjeta.contains("BLACK SIGNATURE")){
    template = fieldtemplate.getText() + "\\template.pdf";   
   }else {
   template = fieldtemplate.getText() + "\\template.pdf";
   bs = new BaseColor (229,21,35);
   }//Cierro condicion de tipo de tarjeta
         
   
    
    } else {
    subproducto = "DD";
    folder = "OtrosX";
    template = fieldtemplate.getText() + "\\template.pdf";
    bs = new BaseColor (229,21,35);
    } //cierro el else
     
       
        SimpleDateFormat sdfDate = new SimpleDateFormat("ddMMyyyy");//dd/MM/yyyy
    Date now = new Date();
    String strDate = sdfDate.format(now);
    String strDateDay = strDate.substring(0,4);
       
       PdfReader reader = null;
       PdfReader reader2 = null;
       
//       seleccionartemplate();
    //   JOptionPane.showMessageDialog(null, ""+ListE.getItemCount());
       
    try {
        reader = new PdfReader(template);
        reader2 = new PdfReader(template);
    } catch (IOException ex) {
        
        log(ex.getMessage());
        
        Logger.getLogger(pdfx.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    String numerocuenta = ListE.getItem(7);
    //JOptionPane.showMessageDialog(null,numerocuenta);
    numerocuenta = numerocuenta.substring(1, numerocuenta.length()-1);
    
    
    
        PdfStamper stamper = null;
    try {
        stamper = new PdfStamper(reader, new FileOutputStream(fieldpublicacion.getText()+"\\"+folder+"\\"+strDateDay+"estado"+ subproducto +"_"+numerocuenta+"_"+strDate+".pdf"));
       
        
      
       
        
       
       
          
        
        
        
        
        name = fieldpublicacion.getText()+"\\"+strDateDay+"cuentas"+ subproducto +"_"+numerocuenta+"_"+strDate+".pdf";
         nombredelpdf = strDateDay+"estado"+ subproducto +"_"+numerocuenta+"_"+strDate+".pdf";
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "ERROR : Directorio de publicacion");
        Logger.getLogger(pdfx.class.getName()).log(Level.SEVERE, null, ex);
        log(ex.getMessage());
    }
       
   PdfContentByte canvas = stamper.getOverContent(pagina);
    Font helvetica = new Font(Font.getFamily("ARIAL"), 8);
             BaseFont bf_helv = helvetica.getCalculatedBaseFont(true);
   
     
    double rep = ListD.getItemCount()/175;
    //JOptionPane.showMessageDialog(null, repeticiones);
             
             
             
        if ((ListD.getItemCount()/5)-1>35){
            repeticiones = (int) Math.round(rep + 0.5);
       //  JOptionPane.showMessageDialog(null, repeticiones);
            
         for(int i=1; i<repeticiones;i++){
            stamper.insertPage(1, reader2.getPageSizeWithRotation(1));
            PdfContentByte page1 = stamper.getOverContent(1);
            PdfImportedPage page = stamper.getImportedPage(reader2, 1);
            page1.addTemplate(page, 0, 0);
            
         }//cierro el for
        
        }    //cierro el if 
    
  int next = 0;
      for (int j=0; j<repeticiones; j++){
          
     //  JOptionPane.showMessageDialog(null, "rep"+(j+1));
 // JOptionPane.showMessageDialog(null, "pagina"+pagina);
    
   
     canvas = stamper.getOverContent(j+1);
        // canvas = stamper.getOverContent(pagina);
         canvas.beginText();
        canvas.setFontAndSize(bf_helv, 8);
        canvas.setColorFill(new BaseColor (18,18,18));
        int numero = 10 ;
        
        
        
        
        //Resumen de la cuenta---------------------------------------------------------------------------
      
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Fecha de hoy", 45, 695+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Fecha Maxima", 45, 685+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Limite", 45, 675+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Disponible", 45, 665+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Pago Mínimo", 45, 655+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Pago Maxima", 45, 645+20, 0);
        
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(8), 200 , 695+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(11), 200 , 685+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(13), 200 , 675+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(16), 200 , 665+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(18), 200 , 655+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(19), 200 , 645+20 , 0 );
        
        //Resumen de transacciones------------------------------------------------------------------------
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Total Compras", 220 , 695+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Total Pagos", 220 , 685+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Número de Cuenta " + ListE.getItem(20), 220 , 645+20, 0);
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(9), 380 , 695+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(14), 380 , 685+20, 0);
        
        //Resumen de Subproducto--------------------------------------------------------------------------
        
        if (ListE.getItem(21).contains("1")){
       
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Puntos ", 395, 695+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Puntos ", 395, 685+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Puntos ", 395, 675+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Puntos ", 395, 665+20, 0);
            
            
        }else {
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Iniciales", 395, 695+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Ganados", 395, 685+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Utilizados", 395, 675+20, 0);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Disponible", 395, 665+20, 0);
            
        }//cierro el else
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(10), 565 , 695+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(12), 565 , 685+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(15), 565 , 675+20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListE.getItem(17), 565 , 665 +20, 0 );
        
        
        
        
        
      //Programa Especiales ---------------------------------------------------------------------------
        
        fila = 615;
        
        String separar = ListE.getItem(21);
        String [] sep ;
        int contador_programas = 22; 
        
        for (int i=0; i<(ListE.getItemCount()-22);i++){
            separar = ListE.getItem(contador_programas);
            sep = separar.split("_", 6);
            
             if (!separar.equals("")){
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, sep[0], 45 , fila , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, sep[1], 110 , fila , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, sep[2], 340 , fila , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, sep[3], 400 , fila , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, sep[4], 480 , fila , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, sep[5], 560 , fila , 0 );
            
        fila = fila - 10;
        contador_programas++;
        cantprogramas = cantprogramas + 10 ;
        }//cierro el if
        
       
        }//cierro el for de programas especiales
        
        
         
    //Agrego HeaderDetalle---------------------------------------------------------------------------------
         
                fila = 635;
         
               Font arialbold = new Font(Font.getFamily("arial"), 8, Font.BOLD, BaseColor.WHITE);                     
               BaseFont bfbold = arialbold.getCalculatedBaseFont(true);
               canvas.setFontAndSize(bfbold, 8);
               canvas.setColorFill(BaseColor.WHITE);
               
                canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Resumen de la Cuenta", 90, 726, 0);
                canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Resumen de transacciones", 255, 726, 0);
              
                if (ListE.getItem(21).contains("1")){
                canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Resumen puntosX", 445, 726, 0);
                }else{
                canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Resumen OtrosX", 445, 726, 0);    
                }//cierro condicion de resumen
         
               canvas.endText();
               
               //sitienenprog
               
               int x = 0;
              
               
               
               
               if (contador_programas > 22) {
              
                  canvas.beginText();
                  
                  
                  
                  canvas.endText();
                   
               canvas.setLineWidth(1);
               canvas.setColorFill(bs);
               canvas.roundRectangle(40, fila , 531, 9, 2);
               canvas.fill();
               
               canvas.setColorStroke(bs);              
               canvas.roundRectangle(40, 626 , 531, 9, 2);
               canvas.stroke();
               
               
               x = 22 ; 
               canvas.setLineWidth(1);
               canvas.setColorFill(bs); 
              // fila = fila - x -cantprogramas;
               canvas.roundRectangle(40, fila - x -cantprogramas , 531, 10, 2);
               canvas.fill();
               
               
               canvas.beginText();
               
               
               Font arialbold2 = new Font(Font.getFamily("arial"), 8, Font.BOLD, BaseColor.WHITE);                     
               BaseFont bfbold2 = arialbold2.getCalculatedBaseFont(true);
               canvas.setFontAndSize(bfbold2, 8);
               canvas.setColorFill(BaseColor.WHITE);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Programas especiales", 252, fila+1, 0);
              
               
               canvas.setColorFill(bs);
               
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Fecha", 60, 627, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Descripción", 120, 626+1, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, "Monto Original", 340, 626+1, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, "Período", 400, 626+1, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, "Cuota", 480, 626+1, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Saldo", 530, 626+1, 0);
               
               
               
               canvas.endText();
               
               
               
               
               
               
               
         //notiene prog          
    } else {
                 
               canvas.setLineWidth(1);
               canvas.setColorFill(bs);
               
               canvas.roundRectangle(40, fila-cantprogramas , 531, 10, 2);
               canvas.fill();
         }//cierro el else
               
             //  FontFactory.register("src\\PDFMaker\\ArialNarrow.ttf","ArialNarrow");
 
    
               Font helvetica3 = new Font(Font.getFamily("arial"), 8, Font.BOLD, BaseColor.WHITE);                     
               BaseFont bf_helv3 = helvetica3.getCalculatedBaseFont(true);
      
             
         // Font font2 = FontFactory.getFont("src\\PDFMaker\\ArialNarrow.ttf",BaseFont.IDENTITY_H, BaseFont.EMBEDDED, 7 , Font.BOLD, BaseColor.WHITE);
         // BaseFont b2 = helvetica3.getBaseFont();
          
         
         canvas.beginText();
         canvas.setColorFill(BaseColor.WHITE);
        
         
        canvas.setFontAndSize(bf_helv3, 8);
        
        
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Fecha", 55, fila-cantprogramas+1-x, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Descripción", 120, fila-cantprogramas+1-x, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "Ciudad", 315, fila-cantprogramas+1-x, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, "Débitos/Compras", 465, fila-cantprogramas+1-x, 0);
               canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, "Créditos/Compras", 565, fila-cantprogramas+1-x, 0);
               
               canvas.endText();
               
          
          

               
               
               
               
         
         //JOptionPane.showMessageDialog(null, "STAHP!");
         
        canvas.beginText();          
        
        Font helvetica4 = new Font(Font.getFamily("arial"), 7, Font.NORMAL, BaseColor.BLACK); 
             BaseFont bf_helv4 = helvetica4.getCalculatedBaseFont(true);
        
        
        canvas.setFontAndSize(bf_helv4, 8);
        canvas.setColorFill(new BaseColor (18,18,18));
       
        


//DEtalle -------------------------------------------------------------------------------------
        
        int y = 0;
        
        int columna = fila-cantprogramas - 10 - x;
        int contmsj = 0;
        
      //JOptionPane.showMessageDialog(null, repeticiones - 1);
      //JOptionPane.showMessageDialog(null, j);
       
     if ((ListD.getItemCount()/5)-1>35){
            
            if(j!=repeticiones-1){
                
              for (int i = 0 ; i < 34 ;i++){
             
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next),   45 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next+1), 110 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next+2), 310 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListD.getItem(next+3), 465 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListD.getItem(next+4), 565 , columna , 0 );
        
        
        
        next = next + 5;
        columna = columna -10;
        
        }//cierro el for  
              
            
            }//cierro el if 0 
            else {
                
              
        // canvas = stamper.getOverContent(pagina);
               //     JOptionPane.showMessageDialog(null, (ListD.getItemCount()/5));
               //     JOptionPane.showMessageDialog(null, (ListD.getItemCount()/5)-(35*(j)));
                  for (int i = -j ; i < (ListD.getItemCount()/5)-(35*(j)+1) ;i++){
             
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next),   45 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next+1), 110 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next+2), 310 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListD.getItem(next+3), 465 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListD.getItem(next+4), 565 , columna , 0 );
        
        next = next + 5;
        columna = columna -10;
        
        }//cierro el for  
              
            }//cierro el else
            
            canvas.endText();
          
      
        }//cierro el if
       
        
        else {
    
        for (int i = 0 ; i < (ListD.getItemCount()/5)-1;i++){
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next),   45 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next+1), 110 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(next+2), 310 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListD.getItem(next+3), 465 , columna , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, ListD.getItem(next+4), 565 , columna , 0 );
        
        next = next + 5;
        columna = columna -10;
        }//cierro el for
        
        canvas.endText();
        
               }
        
        columna = columna -30;
        
         stamper.getOverContent(1);
            canvas.beginText();
            
        canvas.setFontAndSize(bf_helv4, 8);
        canvas.setColorFill(new BaseColor (18,18,18));
        
        BaseFont bfbold2 = arialbold.getCalculatedBaseFont(true);
        
//Mensajes extra detalle -------------------------------------------------------------------------------------------
        
       // for (int i = 0 ; i < ListF.getItemCount();i++){
             for (int i = 0 ; i < ListF.getItemCount();i++){
                 canvas.setFontAndSize(bf_helv4, 8);
                 
                if(ListF.getItem(i).contains("Tasa CAT")){
                canvas.setFontAndSize(bfbold2, 8);
                canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListF.getItem(i),   45 , columna , 0 );
                }else{
                canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListF.getItem(i),   45 , columna , 0 );
                }
            
        
        columna = columna - 10 ;
        }//cierro el for
        //cierro mensajes
        
        canvas.setFontAndSize(bf_helv4, 8);
//Mensaje pie de pagina--------------------------------------------------------------------------------------------------
        
        canvas.setFontAndSize(bf_helv, 6);
        
       // JOptionPane.showMessageDialog(null, next);
       // JOptionPane.showMessageDialog(null, ListD.getItemCount());
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(ListD.getItemCount()-5),   100 , 90-20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(ListD.getItemCount()-4), 100 , 80-20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(ListD.getItemCount()-3), 100 ,70-20 , 0 );
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListD.getItem(ListD.getItemCount()-2), 100 , 60-20 , 0 );
        
  
        
        canvas.endText();
        
    
        Color color = new Color(235, 52, 58); 
        
        
              
    pagina++;
    }//cierro repeticiones
      
    //--------------Mensaje del ESTADO--------------------------------------------------------------------------------------------------------------------
      
    stamper.getOverContent(pagina);
    Font helvetica4 = new Font(Font.getFamily("arial"), 7, Font.NORMAL, BaseColor.BLACK); 
    BaseFont bf_helv4 = helvetica4.getCalculatedBaseFont(true);
    canvas.beginText();
            
        canvas.setFontAndSize(bf_helv4, 8);
        canvas.setColorFill(new BaseColor (18,18,18));
    
    
    int linea = 130;
     for (int i = 0 ; i < ListG.getItemCount();i++){
            
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, ListG.getItem(i),   45 , linea , 0 );
        linea = linea -10 ;
                
     }
    
    canvas.endText();
    //----------------------------------------------------------------------------------------------------------------------------------           
              // JOptionPane.showMessageDialog(null, "go");
    try {
        stamper.close();
    } catch (IOException ex) {
        Logger.getLogger(pdfx.class.getName()).log(Level.SEVERE, null, ex);
        log(ex.getMessage());
    }
        reader.close();
        
        
        
        cantprogramas = 0;
        generarcsv(ListE, folder, subproducto, strDateDay, nombredelpdf, strDate);
        
        
        
       
        
 
    
    
    }
 
    public List detalle(String cuenta, NodeList nList1, NodeList nList2){
        List listD = new List();
        
        for (int temp = 0; temp < nList1.getLength(); temp++) {
            
            Node nNode = nList1.item(temp); 
			Element eElement = (Element) nNode;
                        
                        if(eElement.getAttribute("Datos").equals(cuenta)){
                            listD.add(eElement.getAttribute("Fecha_Consumo"));
                            listD.add(eElement.getAttribute("Descripcion_Mov"));
                            listD.add(eElement.getAttribute("Ciudad"));
                            listD.add(eElement.getAttribute("Debitos"));
                            listD.add(eElement.getAttribute("Creditos"));
                        }
                        
                
        }
        
        
        
        return listD;
    }
    
    public List Encabezado(int cuenta, NodeList nList1){
        List listD = new List();
        
            Node nNode = nList1.item(cuenta);
            if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                Element eElement = (Element) nNode;
                listD.add(eElement.getAttribute("Correo_Electronico"));
                listD.add(eElement.getAttribute("Tipo_Tarjeta"));
                listD.add(eElement.getAttribute("Nombre"));
                listD.add(eElement.getAttribute("Ciudad"));
                listD.add(eElement.getAttribute("NC"));
                listD.add(eElement.getAttribute("Fecha "));
                listD.add(eElement.getAttribute("Compras "));
                listD.add(eElement.getAttribute("Puntosn"));
                listD.add(eElement.getAttribute("Fecha"));
                listD.add(eElement.getAttribute("Puntos"));
                listD.add(eElement.getAttribute("Limite"));
                listD.add(eElement.getAttribute("Total"));
                listD.add(eElement.getAttribute("Puntos"));
                listD.add(eElement.getAttribute("Credito"));
                listD.add(eElement.getAttribute("Puntos"));
                listD.add(eElement.getAttribute("Pagos"));
                listD.add(eElement.getAttribute("Pagos"));
                listD.add(eElement.getAttribute("NumeroDeCuenta"));//
                listD.add(eElement.getAttribute("TipoSeparacion"));
                
            
            }return listD;
        }
    public List Mensajepie(String numero, NodeList nList3, List listTemp){
        
        for (int temp = 0; temp < nList3.getLength(); temp++) {
        Node nNode = nList3.item(temp);
        
            Element eElement = (Element) nNode;
            if(eElement.getAttribute("Datos").equals(numero)){
                listTemp.add(eElement.getAttribute("Descripcion_M1"));
                listTemp.add(eElement.getAttribute("Descripcion_M2"));
                listTemp.add(eElement.getAttribute("Descripcion_M3"));
                listTemp.add(eElement.getAttribute("Descripcion_M4"));
                listTemp.add("");
                return listTemp;
            }   
        
        }
        listTemp.add("");
        listTemp.add("");
        listTemp.add("");
        listTemp.add("");
        listTemp.add("");
        return listTemp;
    
    }
    public List Programa(String numero, NodeList nList2, List Temp){
        String vacio ="";
        
        
        int contprog = 0;
        
        //JOptionPane.showMessageDialog(null,numero);
        for (int temp = 0; temp < nList2.getLength(); temp++) {
        Node nNode = nList2.item(temp);
        
        
      //  JOptionPane.showMessageDialog(null, nList2.getLength());
        
        Element eElement = (Element) nNode;
        
        
         String separar = "";
         String [] sep2;
         
        
            if(eElement.getAttribute("Datos").equals(numero)){
                
                Temp.add(eElement.getAttribute("Programa"));
              
                 
                 contprog ++ ;
            }   
        
        }
       
        if (contprog == 0){
        Temp.add(vacio);
        Temp.add(vacio);
        Temp.add(vacio);
        Temp.add(vacio);
        }
        
         if (contprog == 1){
        Temp.add(vacio);
        Temp.add(vacio);
        Temp.add(vacio);
        
        }
        
         if (contprog == 2){
        Temp.add(vacio);
        Temp.add(vacio);
    
        
        }
        
         if (contprog == 3){
        Temp.add(vacio);
        
        }
        
        
        return Temp;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Correlativo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField fieldcontrol;
    private javax.swing.JTextField fielddetalle;
    private javax.swing.JTextField fieldpublicacion;
    private javax.swing.JTextField fieldtemplate;
    private javax.swing.JButton generar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    // End of variables declaration//GEN-END:variables

    private List Mensaje7(String cuenta, NodeList nList5) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
        List listD = new List();
        
        DecimalFormat decimalFormat = new DecimalFormat("0000");
               // String cuenta = decimalFormat.format(cont+1);
        
        
        for (int temp = 0; temp < nList5.getLength(); temp++) {
            
            Node nNode = nList5.item(temp); 
			Element eElement = (Element) nNode;
                        
                        if(eElement.getAttribute("Datos").equals(cuenta)&&eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add(eElement.getAttribute("Descripcion_M"));
                            
                        }
                        
                
        }//cierro el for
       // JOptionPane.showMessageDialog(null, listD.getItemCount());
        
        
       return listD;
    }

    private List Mensaje8(String cuenta, NodeList nList5) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
        List listD = new List();
        
        DecimalFormat decimalFormat = new DecimalFormat("0000");
               // String cuenta = decimalFormat.format(cont+1);
        
        
        for (int temp = 0; temp < nList5.getLength(); temp++) {
            
            Node nNode = nList5.item(temp); 
			Element eElement = (Element) nNode;
                        
                        if(eElement.getAttribute("Datos").equals(cuenta)&&eElement.getAttribute("Tipo_Reg").equals("3")){
                            listD.add(eElement.getAttribute("Descripcion_M"));
                            
                        }
                        
                
        }//cierro el for
       // JOptionPane.showMessageDialog(null, listD.getItemCount());
        
        
       return listD;
    }
    
    
    
    private void generarcsv(List ListE, String folder, String subproducto, String date, String nombredelpdf , String dateyear) {
        
      //JOptionPane.showMessageDialog(null, "TESTING CSV");
        
      String csv = fieldpublicacion.getText()+"\\"+folder+"\\"+"01Hn"+subproducto+dateyear+Correlativo.getText()+".csv";
      String csverror = fieldpublicacion.getText()+"\\"+folder+"\\"+"ERROR"+subproducto+dateyear+Correlativo.getText()+".csv";
    
      try {
        String correo = ListE.getItem(0);
        
       // JOptionPane.showMessageDialog(null,correo);
        if (correo.contains(",")){
        csv = csverror;
        }//cierro el IF
        
        CSVWriter writer = new CSVWriter(new FileWriter(csv , true),CSVWriter.DEFAULT_SEPARATOR, CSVWriter.NO_QUOTE_CHARACTER,CSVWriter.DEFAULT_ESCAPE_CHARACTER,CSVWriter.RFC4180_LINE_END);
        
        String [] country = {"01Hn"+subproducto+dateyear+Correlativo.getText(),ListE.getItem(7).replace("*", ""),ListE.getItem(2),ListE.getItem(0),nombredelpdf,ListE.getItem(20),ListE.getItem(8),ListE.getItem(11),ListE.getItem(18).replace(",", "").replace("L", ""),ListE.getItem(19).replace(",", "").replace("L", ""),ListE.getItem(16).replace(",", "").replace("L", ""),ListE.getItem(13).replace(",", "").replace("L", ""),ListE.getItem(7).replace("*", ""),archivodetallename.replace(".XML",""),folder.toUpperCase()};
 
       
        
writer.writeNext(country);
 
writer.close();

    } catch (IOException ex) {
        Logger.getLogger(pdfx.class.getName()).log(Level.SEVERE, null, ex);
        
    }
    
    
        
        
        
        
    }//finalizar metodo generarcsv()

    
    private void log(String mistake) throws FileNotFoundException{
    
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
Date date = new Date();
//System.out.println(dateFormat.format(date)); //2014/08/06 15:59:48
        
String error = mistake;
        
        
        resultado.setText("ERROR");
        resultado.setForeground(Color.red);
        
        
        
        try(  PrintWriter out = new PrintWriter( "LOGS.txt" )  ){
         out.println(  dateFormat.format(date) + "  " + error);
}
        
        
        
    }//metodo de logs
    
    
    
    private void ultimomsj(List ListF){
        
        
    
    }//mensaje del estado ultima pagina
    
}
