/*
  <Esto generar un pdf de dos archivos de formato xml pasarlo a un o formato de pdf >
    Copyright 2023  Agrega

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package PDFMaker;

import java.awt.List;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import com.itextpdf.text.*;
import com.itextpdf.text.Chunk;
//import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import static com.itextpdf.text.Font.BOLD;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfImportedPage;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.opencsv.*;
import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.text.DateFormat;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author roberto
 */
public class pdfz extends javax.swing.JFrame {
int cont = 0;

String templatecuerpo = "";
String template = "";
int cantprogramas = 0 ;
String name = "";
String archivodetallename = "0";

int primero = 0 ;
int ultimo  = 0 ; 
int pagina = 1;

    /**
     * Creates new form Menu
     */
    public pdfz() {
        initComponents();
        
//        fieldmaster.setEditable(false);
//        fieldnombre.setEditable(false);
       // fieldprefijo.setText("ESTADOCUENTA");
      //  fieldprefijo.setEditable(false);
        NodeList nList1;
        NodeList nList2;
        this.setResizable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        fieldtemplate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        fielddetalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldcontrol = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        titulo3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        fieldpublicacion = new javax.swing.JTextField();
        generar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        titulo4 = new javax.swing.JLabel();
        Correlativo = new javax.swing.JTextField();
        titulo5 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titulo1.setBackground(new java.awt.Color(204, 204, 204));
        titulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo1.setText("Template textoZ:");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(fieldtemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldtemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titulo2.setBackground(new java.awt.Color(204, 204, 204));
        titulo2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo2.setText("Informacion de Archivos");

        fielddetalle.setEnabled(false);
        fielddetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fielddetalleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Archivo control (Encabezado):");

        fieldcontrol.setEnabled(false);
        fieldcontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcontrolActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Archivo detalle :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldcontrol, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(fielddetalle)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fielddetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldcontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("v.18");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titulo3.setBackground(new java.awt.Color(204, 204, 204));
        titulo3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo3.setText("Carpeta Archivos:");

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        fieldpublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpublicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(fieldpublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldpublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        titulo4.setBackground(new java.awt.Color(204, 204, 204));
        titulo4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo4.setText("Correlativo :");

        Correlativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrelativoActionPerformed(evt);
            }
        });

        titulo5.setBackground(new java.awt.Color(204, 204, 204));
        titulo5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo5.setText("Resultado :");

        resultado.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        resultado.setText("Standby");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(3, 3, 3)
                                            .addComponent(Correlativo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(jButton5)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Correlativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resultado)))
                .addGap(18, 18, 18)
                .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldpublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpublicacionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/Archivos");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fieldpublicacion.setText(chooser.getSelectedFile().getAbsolutePath());
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());         // TODO add your handling code here:
    }    
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/datos");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fieldcontrol.setText(chooser.getSelectedFile().getAbsolutePath());
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/datos");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());
            fielddetalle.setText(chooser.getSelectedFile().getAbsolutePath());
            archivodetallename = chooser.getSelectedFile().getName();
            
        }
    //    JOptionPane.showMessageDialog(null, archivodetallename);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldcontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcontrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcontrolActionPerformed

    private void fielddetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fielddetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fielddetalleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

   
       
       
     //   JOptionPane.showMessageDialog(null, System.getProperty("user.dir")+"/Template");
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir")+"/Template");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            fieldtemplate.setText(chooser.getSelectedFile().getAbsolutePath());
            //System.out.println("You chose to open this directory: " + chooser.getSelectedFile().getAbsolutePath());   
            
        

   
// TODO add your handling code here:
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
      
        
        
        if(fieldtemplate.getText().isEmpty() || fielddetalle.getText().isEmpty() || fieldcontrol.getText().isEmpty() || fieldpublicacion.getText().isEmpty() || Correlativo.getText().isEmpty() ){
       
        JOptionPane.showMessageDialog(null,"Favor llenar todos los campos");
        
        }else{
          resultado.setText("In Process...");
          resultado.setForeground(Color.gray);
         
          
          Nodos();
         
         generar.setVisible(true);
            
        }
        
        
       
    }//GEN-LAST:event_generarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//JOptionPane.showMessageDialog(null, "test");
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CorrelativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrelativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorrelativoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public void Nodos(){
        generar.setVisible(false);
        JOptionPane.showMessageDialog(null, "Este proceso puede tardar varios segundos, favor esperar mensaje de confirmacion");
        
        try{
            File Xml1= new File(fielddetalle.getText());
            File Xml2= new File(fieldcontrol.getText());
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc1 = dBuilder.parse(Xml1);
            Document doc2 = dBuilder.parse(Xml2);            
           
            doc1.getDocumentElement().normalize();
           
           NodeList EncabezadoLempiras = doc2.getElementsByTagName("Encabezado_LEMPIRAS");
           NodeList EncabezadoDolares = doc2.getElementsByTagName("Encabezado_DOLARES");

          System.out.println("Leyo header");
           NodeList DetalleLempiras = doc1.getElementsByTagName("LEMPIRAS");
           NodeList DetalleDolares = doc1.getElementsByTagName("DOLARES");
           NodeList DetallePagos = doc1.getElementsByTagName("Pagos");
            System.out.println("Leyo detalle");
           
           int aumL = 0;
           int aumD = 0;
           
           for (int i =0 ; i < EncabezadoLempiras.getLength() ; i++){//Ciclo PDF
                 Node nNode = EncabezadoLempiras.item(aumL); 
                 Element eElement = (Element) nNode;
                 String inicio = eElement.getAttribute("codigo");
                 int cuentaL = Integer.parseInt(inicio);
                 
                 Node nNode2 = EncabezadoDolares.item(aumD); 
                 Element eElement2 = (Element) nNode2;
                 String inicio2 = eElement2.getAttribute("codigo");
                 int cuentaD = Integer.parseInt(inicio2);
           
               
                 
                 List header = encabezado(EncabezadoLempiras, EncabezadoDolares, aumL, aumD, cuentaL, cuentaD);
                 
                 List detailL = detalle(DetalleLempiras,inicio);
                 List detailD = detalle(DetalleDolares,inicio);
                 List detailP = pagos(DetallePagos,inicio);
                 
                 aumL++;
                 
                 
                 
                 PDFtextoZ(header,detailL,detailD,detailP);
           
                 
                 if (cuentaL==cuentaD&&aumD<EncabezadoDolares.getLength()-1){
                 aumD++;
                 }
           
           }// cierro el for
           
           
           JOptionPane.showMessageDialog(null, "Proceso exitoso ");
           resultado.setText("Success!");
          resultado.setForeground(Color.green);
        }catch (DocumentException | HeadlessException | IOException | NumberFormatException | ParserConfigurationException | SAXException e){
             System.out.println(e.getMessage());
             
            JOptionPane.showMessageDialog(null, "Leyo mal los XML");
           System.exit(0);
           }
           
     //----------------------------------------------------------------------------------------------------------   
        
    }
    
    
    //Fin de ciclo PDF------------------------------------------------------------------------------------------------------------------------------------
    
    
    

    public List detalle(NodeList nList1, String cuentaL){
        List listD = new List();
        
        for (int temp = 0; temp < nList1.getLength(); temp++) {
            
            Node nNode = nList1.item(temp); 
			Element eElement = (Element) nNode;
                        
                        if(eElement.getAttribute("codigo").equals(cuentaL)){
                            listD.add(eElement.getAttribute("Factura"));
                            
                            
                           if (eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add(eElement.getAttribute("Ramo"));
                            }else{
                            listD.add("");
                            }//Ciero el else
                            
                            
                            listD.add(eElement.getAttribute("Vencimiento"));
                            listD.add(eElement.getAttribute("Dias_atraso"));
                            listD.add(eElement.getAttribute("Tipo_Transaccion"));
                            listD.add(eElement.getAttribute("Cuota"));
                            
                            
                             if (eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add(eElement.getAttribute("Moneda"));
                            }else{
                            listD.add("");
                            }//Ciero el else
                            
                            
                            
                            listD.add(eElement.getAttribute("Monto"));
                                  
                            if (eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add("");
                            }else{
                            listD.add(eElement.getAttribute("Descripcion"));
                            }//Ciero el else
                            
                            
                        }
                        
                
        }
       
       
        
        
        
        return listD;
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Correlativo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField fieldcontrol;
    private javax.swing.JTextField fielddetalle;
    private javax.swing.JTextField fieldpublicacion;
    private javax.swing.JTextField fieldtemplate;
    private javax.swing.JButton generar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    // End of variables declaration//GEN-END:variables


    
    private void generarcsv(List ListE, String date, String nombredelpdf , String dateyear) {
        
      //JOptionPane.showMessageDialog(null, "TESTING CSV");
        
      String csv = fieldpublicacion.getText()+"\\textoZ\\"+"01Hn"+dateyear+Correlativo.getText()+".csv";
      String csverror = fieldpublicacion.getText()+"\\"+"\\"+"ERROR"+dateyear+Correlativo.getText()+".csv";
    
      try {
        String correo = ListE.getItem(2);
        
       // JOptionPane.showMessageDialog(null,correo);
        if (correo.contains(",")){
        csv = csverror;
        }//cierro el IF
        
        CSVWriter writer = new CSVWriter(new FileWriter(csv , true),CSVWriter.DEFAULT_SEPARATOR, CSVWriter.NO_QUOTE_CHARACTER,CSVWriter.DEFAULT_ESCAPE_CHARACTER,CSVWriter.RFC4180_LINE_END);
        
        String [] country = {"01Hn"+dateyear+Correlativo.getText(),ListE.getItem(0),ListE.getItem(1).replace(",", " "),ListE.getItem(2).replace(",", " "),nombredelpdf,ListE.getItem(7),ListE.getItem(12).replace(",", " "),ListE.getItem(17).replace(",", " "),ListE.getItem(13).replace(",", " "),ListE.getItem(18).replace(",", " "),archivodetallename.replace(".XML","")};
 
       
        
writer.writeNext(country);
 
writer.close();

    } catch (IOException ex) {
        Logger.getLogger(pdfz.class.getName()).log(Level.SEVERE, null, ex);
        
    }
    
    
        
        
        
        
    }//finalizar metodo generarcsv()
  
    private void PDFtextoZ(List header, List detailL, List detailD, List detailP) throws FileNotFoundException, DocumentException, IOException {
        
      pagina = 1;
    
    SimpleDateFormat sdfDate = new SimpleDateFormat("ddMMyyyy");//dd/MM/yyyy
    Date now = new Date();
    String strDate = sdfDate.format(now);
    String strDateDay = strDate.substring(0,4);
     String nombrePDF = fieldpublicacion.getText()+"\\textoZ\\"+strDateDay+"Estados"+header.getItem(0)+ ".pdf";
    String nombrePDFcortado = "" +strDateDay+"Estados"+header.getItem(0)+ ".pdf";
     
     
         template = fieldtemplate.getText() + "\\Template textoZ.pdf";
         PdfReader reader = null;
       PdfReader reader2 = null;
        int add = header.getItem(3).toString().length() / 4;
      
         
         
         try {
        reader = new PdfReader(template);
        reader2 = new PdfReader(template);
          PdfStamper stamper = null;
           
           stamper = new PdfStamper(reader, new FileOutputStream(nombrePDF));
           
           int test = 1;
          int cantpaginas = ((detailL.getItemCount()/9 + detailD.getItemCount()/9 + detailP.getItemCount()/8)/30)+1;
        //  System.out.println(cantpaginas);
          
          
           do{
           if (test<cantpaginas){
            
            stamper.insertPage(1, reader2.getPageSizeWithRotation(1));
            PdfContentByte page1 = stamper.getOverContent(1);
            PdfImportedPage page = stamper.getImportedPage(reader2, 1);
            page1.addTemplate(page, 0, 0);
            test ++;
          
          }//cierro el if
           }while (test<cantpaginas);
           
           test = 1;
           
           
          PdfContentByte canvas = stamper.getOverContent(pagina);
          Font helvetica = new Font(Font.getFamily("HELVETICA"), 8);
          BaseFont bf_helv = helvetica.getCalculatedBaseFont(true);
          
          Font helvetica2 = new Font(Font.getFamily("HELVETICA"),Font.BOLD, 8);
          BaseFont bf_helv2 = helvetica2.getCalculatedBaseFont(true);
           
           
            
          do{
           
 
        int lineac = 640;
        String add1 = header.getItem(3);
        String add2 = "";
        String add3 = header.getItem(5);
        String add4 = "";
  
         
//Creacion de CABECERA--------------------------------------------------------
       

canvas = stamper.getOverContent(pagina);
           helvetica = new Font(Font.getFamily("HELVETICA"), 8);
           bf_helv = helvetica.getCalculatedBaseFont(true);
          
         helvetica2 = new Font(Font.getFamily("HELVETICA"),Font.BOLD, 8);
         bf_helv2 = helvetica2.getCalculatedBaseFont(true);
 
 
 canvas.beginText();
 canvas.setFontAndSize(bf_helv2, 8);
 canvas.setColorFill(new BaseColor (255,255,255));   
    
    
    

canvas.setFontAndSize(bf_helv2, 8);
      
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "NOMBRE: ", 55 , 650 , 0 );  
        
        canvas.setFontAndSize(bf_helv, 7);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,(header.getItem(0) + " - " + header.getItem(1)), 130 , 650 , 0 ); 
        
         //System.out.println(header.getItem(3).length());
        if (header.getItem(3).length()> 85){
        add1 = add1.substring(0, 85);
        add2 = header.getItem(3).substring(85, header.getItem(3).length()-1);
        //System.out.println(add1 + "--------" + add2);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,add1 , 55 , lineac , 0 ); 
        lineac = lineac -10;
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,add2  , 55 , lineac , 0 ); 
        }else{
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,header.getItem(3)  , 55 , lineac , 0 ); 
        }
        
       
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,header.getItem(4)  , 55 , lineac -10 , 0 );
       
        lineac = lineac -20;
        if (header.getItem(5).length()> 85){
        add3 = add3.substring(0, 85);
        add4 = header.getItem(5).substring(85, header.getItem(5).length()-1);
        //System.out.println(add1 + "--------" + add2);
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,add3  , 55 , lineac , 0 ); 
        lineac = lineac -10;
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,add4  , 55 , lineac , 0 ); 
        }else{
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,header.getItem(5)  , 55 , lineac , 0 ); 
        }
        
        canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT,"CORREO ELECTRONICO: "+header.getItem(2)  , 55 , lineac-10 , 0 );
        
         canvas.setColorFill(new BaseColor (18,18,18));
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, header.getItem(6), 490 , 635 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, header.getItem(7), 490 , 605 , 0 );
         
         
         canvas.setFontAndSize(bf_helv2, 8);
         canvas.setColorFill(new BaseColor (18,18,18));
         
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "LEMPIRAS", 55 , 555 , 0 );  
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_LEFT, "DOLARES", 55 , 542 , 0 );  
         
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(9), 160 , 555 , 0 );
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(10), 250 , 555 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(11), 355 , 555 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(12), 460 , 555 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(13), 545 , 555 , 0 ); 
         
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(14), 160 , 542 , 0 );
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(15), 250 , 542 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(16), 355 , 542 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(17), 460 , 542 , 0 ); 
         canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_RIGHT, header.getItem(18), 545 , 542 , 0 ); 
         
          canvas.endText();
        // System.out.println(pagina + " pagina cabecera");
        // System.out.println(test + " test");
        
          
          test++;
          pagina++;
          
          
}while(test<cantpaginas+1);
          
          
         //  System.out.println(pagina + " pagina");
           
           pagina = 1 ;
           stamper.getOverContent(pagina);
           helvetica = new Font(Font.getFamily("HELVETICA"), 8);
           bf_helv = helvetica.getCalculatedBaseFont(true);
          
         helvetica2 = new Font(Font.getFamily("HELVETICA"),Font.BOLD, 8);
         bf_helv2 = helvetica2.getCalculatedBaseFont(true);
           
           
           int trxL = detailL.getItemCount()/9;
           int linea = 510;
        //Creacion de Detalle Lempiras----------------------------------------------------
         
       
        int canttrx = 0;
       int height = 38;
          int sigln = 0;
          int count = 0;
          BaseColor bs = new BaseColor(194, 40, 32);
      
      
        
          
          for (int j = 0; j < ((detailL.getItemCount()/9)/30)+1; j++){
        
            
         linea = 510;
       //  System.out.println(pagina + " pagina detalle");
        canvas = stamper.getOverContent(pagina);
        helvetica = new Font(Font.getFamily("HELVETICA"), 8);
           bf_helv = helvetica.getCalculatedBaseFont(true);
          
         helvetica2 = new Font(Font.getFamily("HELVETICA"),Font.BOLD, 8);
         bf_helv2 = helvetica2.getCalculatedBaseFont(true);
          
          
          bs = new BaseColor(194, 40, 32);
          canvas.setLineWidth(1);
          canvas.setColorFill(bs);
          canvas.roundRectangle(39, 520 , 540, 12, 2);
          canvas.fill();
               
          
          canvas.beginText();
          canvas.setColorFill(new BaseColor (255,255,255));
          canvas.setFontAndSize(bf_helv2, 8);
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "DETALLE TRANSACCIONES, LEMPIRAS(LPS)", 320 , 523 , 0 ); 
          canvas.endText();
          
        
          
          canvas.beginText();
          canvas.setFontAndSize(bf_helv, 6);
          canvas.setColorFill(new BaseColor (18,18,18));
          
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Factura", 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Vencimiento", 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Días de", 300 , linea , 0 ); 
          
          linea = linea - 6;
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Ramo.Poliza.Recibo", 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Ramo", 160 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Cuota", 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Atraso", 300 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Tipo Transaccion", 400 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Cuota", 470 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Moneda",510 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Monto", 555 , linea , 0 ); 
          
          
          
      //    System.out.println("linea" + linea);
          
          height = 38;
          canttrx =0;
          
          
          for (int i = 0; i < 30; i++){
          
           try{
           detailL.getItem(0+sigln); 
           }catch(Exception e){
            pagina--;   
           break;
           } 
             
          linea = linea - 10;
          
          
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(0+sigln), 70 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(1+sigln), 160 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(2+sigln), 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(3+sigln), 300 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(4+sigln), 400 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(5+sigln), 470 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(6+sigln),510 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(7+sigln), 555 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailL.getItem(8+sigln), 420 , linea , 0 ); 
          sigln = 9+sigln;
          height = height + 10 ;
          canttrx++;
        
          
       
          }//lleno el detalle Lempiras
          
          canvas.endText();
          
         
          
          canvas.setLineWidth(1);
          canvas.setColorStroke(bs);
          canvas.roundRectangle(39, linea - 10 , 540, height, 2);       
          canvas.stroke();
          
          pagina ++;
       //  System.out.println(linea);
        }//cierro el for

         //------------DETALLE DOLARES------------------------------------------------------------------- 
         sigln = 0;
        // System.out.println(linea);
        // JOptionPane.showMessageDialog(null,((detailD.getItemCount()/9)/30) );
         
         for (int j = 0; j < ((detailD.getItemCount()/9)/30)+1; j++){
           canttrx = 0;  
         
         //  System.out.println("Antes del error la pagina esta :" + pagina);
          
          canvas = stamper.getOverContent(pagina);
         
          linea = linea - 30;
         
          
          
          
          canvas.setLineWidth(1);
          canvas.setColorFill(bs);
          canvas.roundRectangle(39, linea , 540, 12, 2);
          canvas.fill();
               
          
          canvas.beginText();
          canvas.setColorFill(new BaseColor (255,255,255));
          canvas.setFontAndSize(bf_helv2, 8);
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "DETALLE TRANSACCIONES, DOLARES(US $)", 320 , (linea+3) , 0 ); 
          canvas.endText();
          
        linea = linea - 13;
          
          canvas.beginText();
          canvas.setFontAndSize(bf_helv, 6);
          canvas.setColorFill(new BaseColor (18,18,18));
          
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Factura", 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Vencimiento", 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Días de", 300 , linea , 0 ); 
          
          linea = linea - 6;
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Ramo.Poliza.Recibo", 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Ramo", 160 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Cuota", 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Atraso", 300 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Tipo Transaccion", 400 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Cuota", 470 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Moneda",510 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Monto", 555 , linea , 0 );
          
          height = 40;
         
       
          for (int i = 0; i < 30; i++){
              
           try{
             detailD.getItem(0+sigln);      
          // System.out.print(detailD.getItem(sigln)); 
           }catch(Exception e){
           break;
           }
          
              
            linea = linea - 10;
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(0+sigln), 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(1+sigln), 160 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(2+sigln), 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(3+sigln), 300 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(4+sigln), 400 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(5+sigln), 470 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(6+sigln),510 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(7+sigln), 555 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailD.getItem(8+sigln), 420 , linea , 0 ); 
          sigln = 9+sigln;
          height = height + 10 ;
          
          canttrx++;
          
           if (linea < 150 ){        
           break;
           }//linea
          
          
          
          }//lleno el detalle Dolares
          
          
          
          canvas.endText(); 
          
       
          
          
          canvas.setLineWidth(1);
          canvas.setColorStroke(bs);
          canvas.roundRectangle(39, linea - 10 , 540, height, 2);       
          canvas.stroke();
          
          
          
          
         if (linea < 150 || canttrx > 30){
           linea = 544;
           pagina++; 
           
           }//linea
          
          
         }//cierro el for
          
        
           
           
           
           
          //---------PAGOS--------------------------------------------------------------------------------------------------------
          
          sigln = 0;
           for (int j = 0; j < ((detailP.getItemCount()/8)/30)+1; j++){
               
               if (pagina>cantpaginas){
               break;
               }
               
          
            canttrx = 0;  
           canvas = stamper.getOverContent(pagina);    
       //   System.out.println("Numero de pagina : "+pagina);
          linea = linea - 30;
          canvas.setLineWidth(1);
          canvas.setColorFill(bs);
          canvas.roundRectangle(39, linea , 540, 12, 2);
          canvas.fill();
          
          canvas.beginText();
          canvas.setColorFill(new BaseColor (255,255,255));
          canvas.setFontAndSize(bf_helv2, 8);
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "DETALLE DE PAGOS RECIBIDOS", 320 , (linea+3) , 0 ); 
          canvas.endText();
          
          linea = linea - 13;
          
          
          canvas.beginText();
          canvas.setFontAndSize(bf_helv, 6);
          canvas.setColorFill(new BaseColor (18,18,18));
          
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Factura", 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Fecha", 250 , linea , 0 ); 
          
          linea = linea - 6;
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Ramo.Poliza.Recibo", 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Ramo", 160 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Recepcion", 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Forma Pago", 370 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Cuota", 470 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Moneda",510 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, "Valor Aplicado", 555 , linea , 0 );
          
          height = 40;
          
          
          
          for (int i = 0; i < 30 ; i++){
              
               try{
              detailP.getItem(0+sigln);     
         
           }catch(Exception e){
           break;
           }
              
              
              
            linea = linea - 10;
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(0+sigln), 70 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(1+sigln), 160 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(2+sigln), 250 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(3+sigln), 370 , linea , 0 ); 
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(4+sigln), 470 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(5+sigln),510 , linea , 0 );  
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(6+sigln), 555 , linea , 0 );
          canvas.showTextAligned(com.itextpdf.text.Element.ALIGN_CENTER, detailP.getItem(7+sigln), 420 , linea , 0 ); 
          sigln = 8+sigln;
          height = height + 10 ;
          
           canttrx++;
          
           //System.out.println("La linea queda en :" + linea);
           if (linea < 150 ){
                    
           break;
           }//linea
          
          
          }//lleno el detalle Pagos
          
          canvas.endText(); 
          
          canvas.setLineWidth(1);
          canvas.setColorStroke(bs);
          canvas.roundRectangle(39, linea - 10 , 540, height, 2);       
          canvas.stroke();
          
          
          
           if (linea < 150 ){
           linea = 544; 
           pagina++; 
           }//linea
          
         if (canttrx > 29){
           linea = 544; 
           pagina++;
           j--;
           }//linea
         
           try{
              detailP.getItem(0+sigln);     
         
           }catch(Exception e){
           break;
           }
         
           
           }//cuerro el for
          
          
         
          //-------------------------------------------------------------------------------------------------------------------------
          
        stamper.close();     
        reader.close();
        
       
    } catch (IOException ex) {
       JOptionPane.showMessageDialog(null, "No se pudo leer el template de PDF indicado");
        Logger.getLogger(pdfx.class.getName()).log(Level.SEVERE, null, ex);
    }//cierro lectura de PDF
         
        
         
        
        generarcsv(header,strDateDay,nombrePDFcortado, strDate);
    }

    private List encabezado(NodeList EncabezadoLempiras, NodeList EncabezadoDolares, int aumL, int aumD, int cuentaL, int cuentaD) {
       
        List listD = new List();
        String codigocliente = "";
        

            Node nNode = EncabezadoLempiras.item(aumL);
            if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                Element eElement = (Element) nNode;
                listD.add(eElement.getAttribute("codigo"));
                codigocliente = eElement.getAttribute("codigo");
                listD.add(eElement.getAttribute("Nombre_cliente"));
                listD.add(eElement.getAttribute("Correo_Eletronico"));
                listD.add(eElement.getAttribute("Direccion"));
                listD.add(eElement.getAttribute("Ciudad"));
                listD.add(eElement.getAttribute("Telefono"));
                listD.add(eElement.getAttribute("Asesor_textoZ"));
                listD.add(eElement.getAttribute("Periodo"));    
                listD.add(eElement.getAttribute("Moneda"));
                listD.add(eElement.getAttribute("Vencido_anterior"));
                listD.add(eElement.getAttribute("Pagos"));
                listD.add(eElement.getAttribute("Transacciones_del_mes"));
                listD.add(eElement.getAttribute("Monto_vencido"));
                listD.add(eElement.getAttribute("Total_a_pagar"));
                listD.add("0");
                listD.add("0");
                listD.add("0");
                listD.add("0");
                listD.add("0");
                 }//cierro el if
                
 
             //System.out.println("Entro al if listD numero -> " + EncabezadoDolares.getLength());
               
               for (int temp = 0; temp < EncabezadoDolares.getLength(); temp++) {
                   
                   Node nNode2 = EncabezadoDolares.item(temp); 
			Element eElement2 = (Element) nNode2;
                                              
                        
                        if(eElement2.getAttribute("codigo").equals(codigocliente)){    
                listD.remove(18);
                 listD.remove(17);
                  listD.remove(16);
                   listD.remove(15);
                    listD.remove(14);
                    
                    
                listD.add(eElement2.getAttribute("Vencido_anterior"));         
                listD.add(eElement2.getAttribute("Pagos"));
                listD.add(eElement2.getAttribute("Transacciones_del_mes"));
                listD.add(eElement2.getAttribute("Monto_vencido"));
                listD.add(eElement2.getAttribute("Total_a_pagar"));
                 break;
                        }//cierro el if 
              
                    
             
                   
               }//cierro el for
               
               
              System.out.println(listD.getItemCount());
               
           
             
            
            return listD;
        
       
    }//cierro metodo cabezera

    private List pagos(NodeList DetallePagos, String cuentaL) {
        List listD = new List();
        //System.out.println("Entro metodo Pagos");
         //System.out.println(DetallePagos.getLength());
         for (int temp = 0; temp < DetallePagos.getLength(); temp++) {
            
            Node nNode = DetallePagos.item(temp); 
			Element eElement = (Element) nNode;
                        
                        if(eElement.getAttribute("codigo").equals(cuentaL)){
                            listD.add(eElement.getAttribute("Factura"));  
                            
                            
                            
                            
                           if (eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add(eElement.getAttribute("Ramo"));
                            }else{
                            listD.add("");
                            }//Ciero el else
                            
                            
                            
                            
                            listD.add(eElement.getAttribute("Fecha_recepcion"));
                            listD.add(eElement.getAttribute("Forma_de_pago"));
                            listD.add(eElement.getAttribute("Cuota"));
                            
                            
                             if (eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add(eElement.getAttribute("Moneda"));
                            }else{
                            listD.add("");
                            }//Ciero el else 
                            
                            
                            
                            listD.add(eElement.getAttribute("Valor_aplicado"));  
                            
                            if (eElement.getAttribute("Tipo_Reg").equals("0")){
                            listD.add("");
                            }else{
                            listD.add(eElement.getAttribute("Descripcion"));
                            }//Ciero el else 


                            
                           
                        }
                        
                //System.out.println(listD.getItemCount());
        }
        
        
        return  listD;
    }
    
}
